language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

sudo: required

addons:
  hostname: keenclient-java
  apt:
    update: true

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7

before_install:

  # Install packages needed to execute Android tools on 64-bit Linux.
  - ./install_prereqs.sh

env:
  - TERM=dumb

install:
  - ./gradlew assemble

script:
  - ./gradlew check
